"""Create comments' title column

Revision ID: 380764a41af0
Revises: 76d4f95eb923
Create Date: 2020-05-15 14:45:14.342091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380764a41af0'
down_revision = '76d4f95eb923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'title')
    # ### end Alembic commands ###
